# Generated by Django 4.2.5 on 2023-09-11 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Uzivatel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=300, unique=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'uživatel',
                'verbose_name_plural': 'uživatelé',
            },
        ),
        migrations.CreateModel(
            name='Zanr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev_zanru', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Kniha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(max_length=200, verbose_name='Název')),
                ('autor', models.CharField(max_length=180, verbose_name='Autor')),
                ('rok_vydani', models.CharField(max_length=180, verbose_name='Publikováno')),
                ('jazyk', models.CharField(max_length=180, verbose_name='Jazyk')),
                ('ISBN10', models.CharField(blank=True, max_length=180)),
                ('ISBN13', models.CharField(blank=True, max_length=180)),
                ('majitel', models.CharField(blank=True, max_length=180, verbose_name='Majitel')),
                ('zanr', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Librapp.zanr', verbose_name='Žánr')),
            ],
        ),
    ]
