# Generated by Django 4.2.5 on 2023-09-11 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Librapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kniha',
            name='majitel',
            field=models.ForeignKey(blank=True, max_length=180, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Librapp.uzivatel', verbose_name='Majitel'),
        ),
    ]
