# Generated by Django 4.2.5 on 2023-09-11 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Librapp', '0002_alter_kniha_majitel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kniha',
            name='majitel',
        ),
    ]
