# Generated by Django 4.2.5 on 2023-09-11 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Librapp', '0004_kniha_majitel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uzivatel',
            old_name='first_name',
            new_name='jmeno',
        ),
        migrations.RenameField(
            model_name='uzivatel',
            old_name='last_name',
            new_name='prijmeni',
        ),
        migrations.RenameField(
            model_name='uzivatel',
            old_name='username',
            new_name='uzivatelske_jmeno',
        ),
    ]
