# Generated by Django 4.2.5 on 2023-09-11 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Librapp', '0005_rename_first_name_uzivatel_jmeno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kniha',
            name='majitel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Librapp.uzivatel', verbose_name='Majitel'),
        ),
    ]
