# Generated by Django 4.2.5 on 2023-09-13 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Librapp', '0006_alter_kniha_majitel'),
    ]

    operations = [
        migrations.AddField(
            model_name='kniha',
            name='podtitul',
            field=models.CharField(blank=True, max_length=200, verbose_name='Podtitul'),
        ),
    ]
