# Generated by Django 4.2.5 on 2023-11-08 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Librapp', '0007_kniha_podtitul'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uzivatel',
            name='jmeno',
            field=models.CharField(max_length=200, verbose_name='Jméno'),
        ),
        migrations.AlterField(
            model_name='uzivatel',
            name='prijmeni',
            field=models.CharField(max_length=200, verbose_name='Příjmení'),
        ),
        migrations.AlterField(
            model_name='uzivatel',
            name='uzivatelske_jmeno',
            field=models.CharField(max_length=200, verbose_name='Uživatelské jméno'),
        ),
    ]
